// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzFW8FGUu7cGgWtC6Lf27F5CI7LQWiPjs',
    appId: '1:570429932571:web:cabb7b941844dd356764be',
    messagingSenderId: '570429932571',
    projectId: 'registerapp-46066',
    authDomain: 'registerapp-46066.firebaseapp.com',
    storageBucket: 'registerapp-46066.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUDEFI-EE_DrRrVNg7drp2g11Ha_L6APk',
    appId: '1:570429932571:android:ace35020a13885796764be',
    messagingSenderId: '570429932571',
    projectId: 'registerapp-46066',
    storageBucket: 'registerapp-46066.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9YPlIluG7B-NEBaz9Uln6XSflNGKiitY',
    appId: '1:570429932571:ios:3ef239610057fee56764be',
    messagingSenderId: '570429932571',
    projectId: 'registerapp-46066',
    storageBucket: 'registerapp-46066.appspot.com',
    iosBundleId: 'com.register.regiterForms',
  );
}
